# Copyright 2018 Cromwell D. Enage
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/multi_array
  - python tools/boostdep/depinst/depinst.py parameter
  - ./bootstrap.sh
  - ./b2 headers

script:
  - TOOLSET=gcc,clang
  - if [ $TRAVIS_OS_NAME == osx ]; then TOOLSET=clang; fi
  - ./b2 --verbose-test libs/config/test//config_info toolset=$TOOLSET || true
  - ./b2 libs/multi_array/test toolset=$TOOLSET

notifications:
  email:
    on_success: never
